### ISSUE TITLE
Impossible to toggle outline (table of contents) in view mode

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#410]
With Nextcloud 25, Text brings an outline view. There's no way to toggle this in view mode currently.

Related: #104

**Comment by herrselent** [comment]
This report is closed but in 25.0.3 it's still an issue. Members can't toggle the outline of a page. Is there any decision being made?

**Comment by max-nextcloud** [comment]
@herrselent could you check which version of the collectives app you are running? The fix landed in 2.2.1 it seems - maybe you are still on an older version?

**Comment by herrselent** [comment]
unfortunately we‘re already using 2.2.1 and still experiencing this. 

So, when I am logged in and my user can edit I can toggle the outline.

Whereas I defined users as members only - they are not allowed to edit pages. these members can‘t toggle the outline. in fact the three dotted menu on the right top is pretty much stripped - doesn‘t show at all.

**Comment by mejo-** [comment]
Dear @herrselent, would you mind to open a new issue about this?

I just tested and I'm able to reproduce hte issue as simple member when edit permissions are limited to admin users. The page-related three dot menu in the title bar is completely missing in this case.

**Comment by mejo-** [comment]
I just opened a new issue about it: https://github.com/nextcloud/collectives/issues/559

**Comment by herrselent** [comment]
with the update to Collectives version 2.3.0 this issue seems to be fixed. 🙏🏼 Thank you!
