### ISSUE TITLE
Guests can't see files when Collectives are enabled

### ISSUE THREAD

**Issue by enoch85** [nextcloud/collectives#863]
### Actual behavior

When using the guests app in combination with Collectives newly invited guest can only see this: 
![image](https://github.com/nextcloud/guests/assets/4511254/168a84d2-70f1-4172-8417-ccf1681be1fd)

Creating a regular user (non admin or admin) doesn't have this behavior, everything shows up as normal.

We checked the Collectives app as a guest user, and even if a Collective is created, it still aren't aware of the mapping for the Collectives folder. It just says something like "Please create a Collective to be able to choose location". Non-guest users doesn't have this issue though.

![image](https://github.com/nextcloud/guests/assets/4511254/8a451921-281e-42fa-a1bd-73059f11149c)

### What we tried:
1. Remove all the limitations in the Guests app
2. Disable Collectives app

In both cases, the same issue appears.

### Expected behavior
When a new user is invited, they should be able to see everything, just as a normal user.

### Settings:
![image](https://github.com/nextcloud/guests/assets/4511254/ffb2254c-d08e-45a1-adb6-87b47969d5f8)

**Nextcloud version**
27.0.2

**PHP**
8.2

**Server**
Ubuntu server 22.04

**Comment by small1** [comment]
@juliushaertl it also affects if you have files shared to a folder we have one called "/Shared with me"  in this case.  That doesnt work either.

**Comment by enoch85** [comment]
@small1 Can you create the issue report on server an link it here please?

**Comment by max-nextcloud** [comment]
> ```
> TypeError: OC\User\User::__construct(): Argument #3 ($dispatcher) must be of type Symfony\Component\EventDispatcher\EventDispatcherInterface, OC\EventDispatcher\EventDispatcher given,
> ```
That's a different issue. It's tracked as #828 - you can find a patch there and we're working on making the fix available with a new release.

**Comment by quenenni** [comment]
Then, very sorry for my post. The search for my error pointed me to this post.

Indeed the new version was availabe and I updated all the clouds using the app.
I'll see what's what and will go on the right issue if I still have problems.

Thanks for your help.

PS: Just say the word if you want me to delete my post here to not pollute this one. My posts didn't brnig any new informations.

**Comment by max-nextcloud** [comment]
Removed the logs from the description as the exception thrown there is tracked in #828 and fixed now.

@enoch85 Could you check if the latest release of collectives (2.7.1) also fixed this issue for you?

**Comment by enoch85** [comment]
@max-nextcloud It's 50% solved.

Users can now see shared documents, but they still get the message "This folder is best shown in Collectives", and "You don't have permission to upload anything here".

![Screenshot_2023-09-14-08-27-50-97_3aea4af51f236e4932235fdada7d1643](https://github.com/nextcloud/collectives/assets/4511254/e32be212-114b-40c9-8ca9-588a90a7ac6b)

**Comment by max-nextcloud** [comment]
How did you invite the guest users?
My understanding is that they typically are granted access by sharing a file with them. Is that what you did? Which file did you share? Is it part of a collectives folder or so?

The message "You don't have permission to upload anything here" is correct, right? I mean these are guest accounts and they are not in a writeable share folder.

**Comment by small1** [comment]
We invite them in the guests app. What happens is that the collective folder can't be created and thus thinks that / should be the folder to store everything in. 

If we create that manually and scan the users files it will work as it should

**Comment by enoch85** [comment]
@max-nextcloud 

Yes, user was "created" (rather activated) by sharing Testdockument.txt through email to my own user [email redacted].

I'm not sure about the permissions, but you're probably right. Though the file is *not* part of Collectives and has nothing to do with Collectives at all.

**Comment by max-nextcloud** [comment]
Hum... just a wild guess. Maybe collectives cannot create the folder for it's mountpoints - falls back to the root folder and from there on thinks all folders are belong to it.

Funny thing is that we have not observed this behavior on our own instance with guest users.

**Comment by max-nextcloud** [comment]
@enoch85 Could you share the Collectives folder with them? I'd be curious what happens then:
* The user should now have a folder with the correct name to put collectives into. So maybe it stops treating the root folder as one?
* The folder contains the mount points of your own collectives. I don't know if they will be shared as well. Would be curious to hear.

**Comment by small1** [comment]
@max-nextcloud I did that test when we filed the bug. Folder wasn't created. It started working correctly after we created the collective folder manually
